@echo off
echo Arrancando Sistema de Depreciacion...

echo Iniciando Backend...
start "Backend API" cmd /k "cd backend\IndentityService && dotnet run"

echo Iniciando Frontend...
start "Frontend React" cmd /k "cd frontend && npm run dev"